name: Jest Unit Tests

on:
  pull_request:
    branches:
      main

jobs: 
  tests: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: ./source
        run: npm ci

      - name: Code Linting
        working-directory: ./source 
        run: npm run test
